// Copyright (c) CodeBlock.Dev. All rights reserved.
// See LICENSE in the project root for license information.

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeBlock.DevKit.Web.Blazor.Server.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class BlazorResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BlazorResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CodeBlock.DevKit.Web.Blazor.Server.Resources.BlazorResource", typeof(BlazorResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trying to connect to the server. Please wait....
        /// </summary>
        public static string Connection_State_Disconnect_Content {
            get {
                return ResourceManager.GetString("Connection_State_Disconnect_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection lost!.
        /// </summary>
        public static string Connection_State_Disconnect_Title {
            get {
                return ResourceManager.GetString("Connection_State_Disconnect_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong! please refresh the page using the button below.
        /// </summary>
        public static string Connection_State_Error_Content {
            get {
                return ResourceManager.GetString("Connection_State_Error_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong!.
        /// </summary>
        public static string Connection_State_Error_Title {
            get {
                return ResourceManager.GetString("Connection_State_Error_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unfortunately, the automatic attempt to reconnect with the server was not successful, please try again through the button below.
        /// </summary>
        public static string Connection_State_Reconnect_Content {
            get {
                return ResourceManager.GetString("Connection_State_Reconnect_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection was not successful!.
        /// </summary>
        public static string Connection_State_Reconnect_Title {
            get {
                return ResourceManager.GetString("Connection_State_Reconnect_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The connection with the server is established, but the connection request was rejected from the server side. Please try again using the button below..
        /// </summary>
        public static string Connection_State_Reject_Content {
            get {
                return ResourceManager.GetString("Connection_State_Reject_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection request was rejected!.
        /// </summary>
        public static string Connection_State_Reject_Title {
            get {
                return ResourceManager.GetString("Connection_State_Reject_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reload.
        /// </summary>
        public static string Connection_State_Reload_Btn {
            get {
                return ResourceManager.GetString("Connection_State_Reload_Btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retry connection.
        /// </summary>
        public static string Connection_State_Retry_Btn {
            get {
                return ResourceManager.GetString("Connection_State_Retry_Btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We are authorizing, please wait..
        /// </summary>
        public static string Error_Authorization_Message {
            get {
                return ResourceManager.GetString("Error_Authorization_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorizing ....
        /// </summary>
        public static string Error_Authorization_Title {
            get {
                return ResourceManager.GetString("Error_Authorization_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry! It seems the page that you are looking for, does not exist..
        /// </summary>
        public static string Error_NotFound_Message {
            get {
                return ResourceManager.GetString("Error_NotFound_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page not found!.
        /// </summary>
        public static string Error_NotFound_Title {
            get {
                return ResourceManager.GetString("Error_NotFound_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We are sorry! We were unable to process your request at this time. Our technical team was informed about this issue and it will be investigated soon. Thank you for your patience..
        /// </summary>
        public static string Error_Page_Content {
            get {
                return ResourceManager.GetString("Error_Page_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to home page!.
        /// </summary>
        public static string Error_Page_Home_Btn {
            get {
                return ResourceManager.GetString("Error_Page_Home_Btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong!.
        /// </summary>
        public static string Error_Page_Title {
            get {
                return ResourceManager.GetString("Error_Page_Title", resourceCulture);
            }
        }
    }
}

